import glob, sys#, fitz
from glob import glob
import re
from os import path

def find_ext(dr, ext):
    return glob(path.join(dr,"*.{}".format(ext)))


pythonfiles = \
    [
    "helper.py",
    "abstract/vector.py",    
    "geometry/point.py",
    "project/fileformat.py",
    "abstract/coordinatesystem.py",
    "abstract/boundingbox.py",
    "geometry/curve.py",
    "abstract/node.py",
    "abstract/color.py",
    "abstract/image.py",
    "abstract/interval.py",
    "abstract/plane.py",
    "abstract/text.py",
    "geometry/bmesh.py",
    "geometry/geometry2d.py",
    "abstract/intersect.py",
    "abstract/intersect2d.py",
    "geometry/linestyle.py",
    "geometry/pointcloud.py",
    "geometry/solid.py",
    "geometry/surface.py",
    "objects/panel.py",
    "geometry/systemsimple.py",
    "library/material.py",
    "library/profile.py",
    "objects/analytical.py",
    "objects/annotation.py",
    "objects/datum.py",
    "objects/frame.py",
    "objects/objectcollection.py",
    "objects/shape.py",
    "objects/shape3d.py",
    "objects/steelshape.py",
    "objects/view.py",
    "exchange/DXF.py",
    "exchange/pat.py",
    "exchange/struct4U.py",
    "exchange/scia.py"
    ]

#if export to revit, add this line:     "exchange/revit.py"

BuildingPySingleFileStr = ""
Includedstr = "# [included in BP singlefile]"

for i in pythonfiles:
    with open(i) as f:
        str = f.read()
        if Includedstr in str:
            BuildingPySingleFileStr = BuildingPySingleFileStr + str

start = '# [!not included in BP singlefile - start]'
end = '# [!not included in BP singlefile - end]'
s = BuildingPySingleFileStr

test2 = ((s.split(start))[1].split(end)[0])

i = 0
max = BuildingPySingleFileStr.count(start)

for j in range(max):
    try:
        substringtoremove = (BuildingPySingleFileStr.split(start))[1].split(end)[0]
        BuildingPySingleFileStr = BuildingPySingleFileStr.replace(substringtoremove, "")
        BuildingPySingleFileStr = BuildingPySingleFileStr.replace(start, "",1)
        BuildingPySingleFileStr = BuildingPySingleFileStr.replace(end, "",1)
    except:
        print("out of range")

BuildingPySingleFileStr = BuildingPySingleFileStr.replace(Includedstr, "")

BuildingPySingleFileStr_NoImports = ""

for line in BuildingPySingleFileStr.split("\n"):
    if "from " in line and "#" not in line:
        pass
    elif "import " in line and "#" not in line:
        pass
    else:
        BuildingPySingleFileStr_NoImports = BuildingPySingleFileStr_NoImports + "\n" + line
BuildingPySingleFileStr = BuildingPySingleFileStr_NoImports

startstr = "#[BuildingPy] DO NOT EDIT THIS FILE. IT IS GENERATED FROM THE SOURCE CODE\n" \
    "import math\n" \
    "import sys\n" \
    "import os\n" \
    "#import requests\n" \
    "import json\n" \
    "from collections import defaultdict\n" \
    "import subprocess\n" \
    "import urllib\n" \
    "import time\n" \
    "import urllib.request\n" \
    "import string\n" \
    "import random\n" \
    "from typing import List, Tuple\n" \
    "import xml.etree.ElementTree as ET\n" \
    "from pathlib import Path\n" \
    "#import numpy as np\n" \
    "#import ezdxf\n" \
    "#from svg.path import parse_path\n"

BuildingPySingleFileStr = startstr + BuildingPySingleFileStr

with open('bp_single_file.py', 'w+') as fh:
    fh.write(BuildingPySingleFileStr)