import glob, sys#, fitz
from glob import glob
import re
from os import path

flagLocal = True

def find_ext(dr, ext):
    return glob(path.join(dr,"*.{}".format(ext)))

pythonfiles = \
    [
    "BuildingPy.py",
    "packages/GIS2BIM/GIS2BIM.py",
    "packages/GIS2BIM/GIS2BIM_NL.py",
    "packages/GIS2BIM/GIS2BIM_NL_helpers.py",
    "packages/GIS2BIM/GIS2BIM_CityJSON.py",
    "packages/GIS2BIM/GIS2BIM_CRS.py"
    ]

prefix = "C:/Users/mikev/Documents/GitHub/building.py/"

if flagLocal:
    pythonfiles2 = []
    for i in pythonfiles:
        pythonfiles2.append(prefix + i)

    pythonfiles = pythonfiles2

else:
    pass

GIS2BIMSingleFileStr = ""
Includedstr = "# [included in GIS2BIM singlefile]"

for i in pythonfiles:
    with open(i) as f:
        str = f.read()
        if i == "packages/svg/path/parser.py":
            str = str.replace("path.", "")
        if Includedstr in str:
            GIS2BIMSingleFileStr = GIS2BIMSingleFileStr + str

start = '# [!not included in GIS2BIM singlefile - start]'
end = '# [!not included in GIS2BIM singlefile - end]'
s = GIS2BIMSingleFileStr

test2 = ((s.split(start))[1].split(end)[0])

i = 0
max = GIS2BIMSingleFileStr.count(start)

for j in range(max):
    try:
        substringtoremove = (GIS2BIMSingleFileStr.split(start))[1].split(end)[0]
        GIS2BIMSingleFileStr = GIS2BIMSingleFileStr.replace(substringtoremove, "")
        GIS2BIMSingleFileStr = GIS2BIMSingleFileStr.replace(start, "",1)
        GIS2BIMSingleFileStr = GIS2BIMSingleFileStr.replace(end, "",1)
        GIS2BIMSingleFileStr = GIS2BIMSingleFileStr.replace("GIS2BIM.","")
    except:
        print("out of range")

GIS2BIMSingleFileStr = GIS2BIMSingleFileStr.replace(Includedstr, "")

GIS2BIMSingleFileStr_NoImports = ""

for line in GIS2BIMSingleFileStr_NoImports.split("\n"):
    if "from " in line and "#" not in line and len(line) < 20:
        pass
    elif "import " in line and "#" not in line:
        pass
    else:
        GIS2BIMSingleFileStr_NoImports = GIS2BIMSingleFileStr_NoImports + "\n" + line
#GIS2BIMSingleFileStr = GIS2BIMSingleFileStr_NoImports

startstr = "#[GIS2BIM] DO NOT EDIT THIS FILE. IT IS GENERATED FROM THE SOURCE CODE\n" \
    "import urllib\n" \
    "import urllib.request\n" \
    "from urllib.request import urlopen\n" \
    "import xml.etree.ElementTree as ET\n" \
    "import json\n" \
    "import math\n" \
    "import re\n" \
    "from zipfile import ZipFile\n" \
    "import time\n" \
    "import ijson\n" \
    "import sys\n" \
    "import urllib\n" \

GIS2BIMSingleFileStr = startstr + GIS2BIMSingleFileStr

with open('C:/Users/mikev/Documents/GitHub/building.py/GIS2BIM_single_file.py', 'w+') as fh:
    fh.write(GIS2BIMSingleFileStr)