name: Generate bp_single_file

on:
  push:
    paths:
      - 'docs/write_bp_single_file.py'
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Execute Python script
        run: |
          python docs/write_bp_single_file.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add bp_single_file.py
          git commit -m "Automatically updated bp_single_file.py" || true
          git push
